title: Max Mazzocchi
email: maxwell.mazzocchi@gmail.com
description: >-
  Max Mazzocchi is a software developer in Washington, DC.
baseurl: ""
url: "https://maxmazzocchi.com"
github_username:  MMazzocchi

theme: minima

plugins:
  - jekyll-feed
